### PR TITLE
Metanorma fix

### PR DESCRIPTION
**Pull request by ronaldtse**
Temporary fix for metanorma/metanorma-cli#189

P.S. I've also removed the `metanorma setup` step which fails here (https://github.com/usnistgov/ACVP/pull/1088/checks?check_run_id=1510919667) since it's been subsumed by automatic behavior (no manual `setup`) is now necessary.

### CODE REVIEW

**Comment by ronaldtse** [comment]
Build passed! 😉

**Comment by Kritner** [comment]
Thanks @ronaldtse, though I am still seeing a lot of:

```
RFC XML: xref target testtypes does not exist in the document
Cannot continue processing
```

within the build log, which granted, should be fixed on our end; but I don't think this was something we recently changed.  Those particular lines are "failing" the build for those documents, but not overall for the build step itself.

If they are "errors" and not just warnings, shouldn't the build process be returning a failing status code rather than passing?

**Comment by ronaldtse** [comment]
I believe the gem "bundle" isn't reading the proper Gemfile requirements because of where the Gemfile is located (under `src/` instead of under `./`). The `gemfile-to-bundle-add.sh` might not be working as expected here...?

@camobap can you please help check? Hoping you can fix it. Thanks!

**Comment by ronaldtse** [comment]
@Kritner I've reverted previous changes and addressed the issue more comprehensively, by adding blank lines around `include`s.

In addition, this PR now:
* fixes a misspelling in the GHA workflow ("syncronize" => "synchronize"), which caused the current PR not to build
* converts NIST/FIPS and IEEE references to auto-fetching so that you don't need to maintain the metadata of them anymore

Hope this helps!

cc: @celic

**Comment by ronaldtse** [comment]
Grrr: tools.ietf.org is offline again. Will re-run a bit later...

**Comment by Kritner** [comment]
reran and confirmed all artifacts are being generated.  LGTM, thanks!

**Comment by ronaldtse** [comment]
Thanks @Kritner for the confirmation!

**Pull request merged**
